# Generated by Django 2.0.3 on 2019-02-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dinnerplatterorder_pastaorder_saladorder_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatterorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saladorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
