# Generated by Django 2.0.3 on 2019-02-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20190202_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('date', models.TimeField()),
                ('dinnerplatter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.DinnerPlatterOrder')),
                ('pasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.PastaOrder')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.PizzaOrder')),
                ('salad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.SaladOrder')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.SubOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
