# Generated by Django 2.0.3 on 2019-02-02 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20190202_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastorder',
            name='dinnerplatter',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='dinnerplatter',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='pasta',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='pasta',
            field=models.ManyToManyField(blank=True, related_name='pasta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='pizza', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='salad',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='salad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='sub',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='user',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
