# Generated by Django 2.0.3 on 2019-02-02 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20190202_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorder',
            name='dinnerplatter',
            field=models.ManyToManyField(blank=True, related_name='dinnerplatter', to='orders.DinnerPlatterOrder'),
        ),
        migrations.RemoveField(
            model_name='pastorder',
            name='user',
        ),
        migrations.AddField(
            model_name='pastorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
