# Generated by Django 2.0.3 on 2019-02-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190202_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorder',
            name='pasta',
            field=models.ManyToManyField(blank=True, related_name='pasta', to='orders.PastaOrder'),
        ),
        migrations.AlterField(
            model_name='pastorder',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.PizzaOrder'),
        ),
        migrations.AlterField(
            model_name='pastorder',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='salad', to='orders.SaladOrder'),
        ),
        migrations.AlterField(
            model_name='pastorder',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='subs', to='orders.SubOrder'),
        ),
    ]
