# Generated by Django 2.0.3 on 2019-02-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_auto_20190204_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('date', models.TimeField()),
                ('dinnerplatter', models.ManyToManyField(blank=True, related_name='dinnerplatter', to='orders.DinnerPlatterOrder')),
                ('pasta', models.ManyToManyField(blank=True, related_name='pasta', to='orders.PastaOrder')),
                ('pizza', models.ManyToManyField(blank=True, related_name='pizza', to='orders.PizzaOrder')),
                ('salad', models.ManyToManyField(blank=True, related_name='salad', to='orders.SaladOrder')),
                ('sub', models.ManyToManyField(blank=True, related_name='subs', to='orders.SubOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='item',
            field=models.CharField(default='Dinner Platter', max_length=65),
        ),
        migrations.AddField(
            model_name='pasta',
            name='item',
            field=models.CharField(default='Pasta', max_length=65),
        ),
        migrations.AddField(
            model_name='pizza',
            name='item',
            field=models.CharField(default='Pizza', max_length=65),
        ),
        migrations.AddField(
            model_name='salad',
            name='item',
            field=models.CharField(default='Salad', max_length=65),
        ),
        migrations.AddField(
            model_name='sub',
            name='item',
            field=models.CharField(default='Sub', max_length=65),
        ),
    ]
